In [70]:
import pandas as pd

In [72]:

# Load your cleaned weather data
weather_df = pd.read_csv("../cleaned_climate_data.csv")

# Load the SimpleMaps cities dataset
simple_map_cities_df = pd.read_csv("../worldcities.csv")

In [73]:
weather_df.head()

,city,month,country,high_temp_F,low_temp_F,mean_temp_F,precipitation_in,humidity_percent,dew_point_F,wind_mph,pressure_Hg,visibility_mi
0,Accra,January,Ghana,89.0,75.0,82.0,1.57,75.0,73.0,14.0,29.85,5.0
1,Accra,February,Ghana,90.0,77.0,84.0,1.79,77.0,75.0,17.0,29.84,6.0
2,Accra,March,Ghana,91.0,78.0,84.0,2.29,78.0,76.0,17.0,29.83,7.0
3,Accra,April,Ghana,90.0,78.0,84.0,2.93,78.0,76.0,16.0,29.83,7.0
4,Accra,May,Ghana,89.0,77.0,83.0,5.11,80.0,75.0,15.0,29.87,8.0

In [74]:
simple_map_cities_df.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,39105000.0,1.392686e+09
1,Jakarta,Jakarta,-6.1753,106.8269,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1.360771e+09
2,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1.156237e+09
3,Mumbai,Mumbai,19.0758,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1.356227e+09
4,Shanghai,Shanghai,31.2325,121.4692,China,CN,CHN,Shanghai,admin,24870895.0,1.156074e+09

In [75]:
simple_map_countries = simple_map_cities_df['country'].unique()
print(f"Total number of contries in simple map df: {len(simple_map_countries)}")

Total number of contries in simple map df: 242

In [76]:
weather_countries = weather_df['country'].unique()
print(f"Total number of contries in weather df: {len(weather_countries)}")

Total number of contries in weather df: 92

In [77]:
diff = set(weather_countries).difference(set(simple_map_countries))
print(diff)

{'Congo Demrep', 'Bahamas', 'Kazakstan', 'Czech Republic', 'South Korea', 'USA', 'UK', 'Myanmar'}

In [78]:
# A list of keywords to search for in the SimpleMaps country column
search_terms = [
    'Congo', 
    'Bahama', 
    'Kazak', 
    'Czech', 
    'Kore', 
    'United',  # For USA and UK
    'Myanmar', 
    'Burma'    # Sometimes Myanmar is listed as Burma
]

print("--- SimpleMaps Country Matches ---")
for term in search_terms:
    # Find all unique country names that contain the search term
    matches = simple_map_cities_df[
        simple_map_cities_df['country'].str.contains(term, case=False, na=False)
    ]['country'].unique()
    
    print(f"Searching '{term}': {matches}")

--- SimpleMaps Country Matches ---
Searching 'Congo': ['Congo (Kinshasa)' 'Congo (Brazzaville)']
Searching 'Bahama': ['Bahamas, The']
Searching 'Kazak': ['Kazakhstan']
Searching 'Czech': ['Czechia']
Searching 'Kore': ['Korea, South' 'Korea, North']
Searching 'United': ['United States' 'United Kingdom' 'United Arab Emirates']
Searching 'Myanmar': []
Searching 'Burma': ['Burma']

In [79]:
country_corrections = {
    "Congo Demrep": "Congo (Kinshasa)",
    "Bahamas": "Bahamas, The",
    "Kazakstan": "Kazakhstan",
    "Czech Republic": "Czechia",
    "South Korea": "Korea, South",
    "USA": "United States",
    "UK": "United Kingdom",
    "Myanmar": "Burma"
}

# Apply the corrections to scraped weather data
weather_df['country'] = weather_df['country'].replace(country_corrections)

In [80]:
simple_map_countries = simple_map_cities_df['country'].unique()
print(f"Total number of contries in simple map df: {len(simple_map_countries)}")

weather_countries = weather_df['country'].unique()
print(f"Total number of contries in weather df: {len(weather_countries)}")

diff = set(weather_countries).difference(set(simple_map_countries))
print(f"Countries in weather df but not in simple map df: {diff}")

Total number of contries in simple map df: 242
Total number of contries in weather df: 92
Countries in weather df but not in simple map df: set()

In [81]:
simple_map_cities = simple_map_cities_df['city_ascii'].unique()
print(f"Total number of cities in simple map df: {len(simple_map_cities)}")

Total number of cities in simple map df: 46263

In [82]:
weather_cities = weather_df['city'].unique()
print(f"Total number of cities in weather df: {len(weather_cities)}")

Total number of cities in weather df: 140

In [83]:
diff = set(weather_cities).difference(set(simple_map_cities))
print(diff)

{'Yangon', 'Kiritimati', 'Bengaluru', 'Zürich', 'Montréal', 'São Paulo', 'Washington DC'}

In [84]:
# A list of partial names to search for in the SimpleMaps city column
search_cities = [
    'Yangon', 'Rangoon',      # Checking both names for Myanmar's largest city
    'Kiritimati', 'Christmas',# Kiritimati is also known as Christmas Island
    'Bengaluru', 'Bangalore', # Checking both names for the Indian city
    'Zurich',                 # Stripped of the umlaut
    'Montreal',               # Stripped of the accent
    'Sao Paulo',              # Stripped of the tilde
    'Washington'              # Checking Washington DC
]

print("--- SimpleMaps City Matches ---")
for term in search_cities:
    # Find all unique city names that contain the search term
    matches = simple_map_cities_df[
        simple_map_cities_df['city_ascii'].str.contains(term, case=False, na=False)
    ]['city_ascii'].unique()
    
    # We only print if it actually found a match to keep the output clean
    if len(matches) > 0:
        print(f"Searching '{term}': {matches}")

--- SimpleMaps City Matches ---
Searching 'Rangoon': ['Rangoon']
Searching 'Bangalore': ['Bangalore']
Searching 'Zurich': ['Zurich' 'Lake Zurich']
Searching 'Montreal': ['Montreal']
Searching 'Sao Paulo': ['Sao Paulo' 'Sao Paulo de Olivenca' 'Sao Paulo do Potengi']
Searching 'Washington': ['Washington' 'New Washington' 'Fort Washington' 'Mount Washington'
 'Port Washington' 'Washington Court House' 'Washington Terrace']

In [85]:
city_corrections = {
    "Washington DC": "Washington",
    "Montréal": "Montreal",
    "São Paulo": "Sao Paulo",
    "Zürich": "Zurich",
    "Bengaluru": "Bangalore",
    "Yangon": "Rangoon" 
}

# Apply the corrections to your scraped weather data
weather_df['city'] = weather_df['city'].replace(city_corrections)

In [86]:
simple_map_cities = simple_map_cities_df['city_ascii'].unique()
print(f"Total number of cities in simple map df: {len(simple_map_cities)}")

weather_cities = weather_df['city'].unique()
print(f"Total number of cities in weather df: {len(weather_cities)}")

diff = set(weather_cities).difference(set(simple_map_cities))
print(f"Cities in weather df but not in simple map df: {diff}")

Total number of cities in simple map df: 46263
Total number of cities in weather df: 140
Cities in weather df but not in simple map df: {'Kiritimati'}

In [88]:
# The SimpleMaps file has lots of columns (lat, lng, iso3, etc.)
cities_subset = simple_map_cities_df[['city_ascii', 'country', 'population', 'lat', 'lng']]

# Rename 'city_ascii' to 'city' so it  matches weather dataframe
cities_subset = cities_subset.rename(columns={'city_ascii': 'city'})

# Perform a Left Join (Merge)
# Look at the weather data, finds the matching city AND country 
# in the SimpleMaps data, and attaches the population and density.
final_df = pd.merge(
    weather_df, 
    cities_subset, 
    on=['city', 'country'], # We match on BOTH to avoid confusing Paris, France with Paris, Texas
    how='left' # 'left' ensures we keep all 143 weather rows, even if a city is missing
)

# Check the results!
print(final_df[['city', 'country', 'month', 'mean_temp_F', 'population']].head(12))

     city country      month  mean_temp_F  population
0   Accra   Ghana    January         82.0   1782150.0
1   Accra   Ghana   February         84.0   1782150.0
2   Accra   Ghana      March         84.0   1782150.0
3   Accra   Ghana      April         84.0   1782150.0
4   Accra   Ghana        May         83.0   1782150.0
5   Accra   Ghana       June         80.0   1782150.0
6   Accra   Ghana       July         79.0   1782150.0
7   Accra   Ghana     August         78.0   1782150.0
8   Accra   Ghana  September         79.0   1782150.0
9   Accra   Ghana    October         80.0   1782150.0
10  Accra   Ghana   November         82.0   1782150.0
11  Accra   Ghana   December         82.0   1782150.0

In [66]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860 entries, 0 to 1859
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           1860 non-null   object
 1   month          1860 non-null   object
 2   country        1860 non-null   object
 3   high_temp      1860 non-null   object
 4   low_temp       1860 non-null   object
 5   mean_temp      1860 non-null   object
 6   precipitation  1860 non-null   object
 7   humidity       1860 non-null   object
 8   dew_point      1860 non-null   object
 9   wind           1860 non-null   object
 10  pressure       1860 non-null   object
 11  visibility     1848 non-null   object
 12  population     1848 non-null   float64
 13  lat            1848 non-null   float64
 14  lng            1848 non-null   float64
dtypes: float64(3), object(12)
memory usage: 218.1+ KB

In [89]:
# Filter for rows where population is NaN, then get the unique city names
missing_cities = final_df[final_df['population'].isna()]['city'].unique()

print(f"Total missing cities: {len(missing_cities)}")
print(missing_cities)

Total missing cities: 1
['Kiritimati']

In [90]:
# Manually inject Kiritimati's population (~7,380) and coordinates
final_df.loc[final_df['city'] == 'Kiritimati', 'population'] = 7380
final_df.loc[final_df['city'] == 'Kiritimati', 'lat'] = 1.8709
final_df.loc[final_df['city'] == 'Kiritimati', 'lng'] = -157.4276

In [91]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1860 entries, 0 to 1859
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   city              1860 non-null   object
 1   month             1860 non-null   object
 2   country           1860 non-null   object
 3   high_temp_F       1860 non-null   float64
 4   low_temp_F        1860 non-null   float64
 5   mean_temp_F       1860 non-null   float64
 6   precipitation_in  1860 non-null   float64
 7   humidity_percent  1860 non-null   float64
 8   dew_point_F       1860 non-null   float64
 9   wind_mph          1860 non-null   float64
 10  pressure_Hg       1860 non-null   float64
 11  visibility_mi     1848 non-null   float64
 12  population        1860 non-null   float64
 13  lat               1860 non-null   float64
 14  lng               1860 non-null   float64
dtypes: float64(12), object(3)
memory usage: 218.1+ KB

In [93]:
# Save your final enriched dataset
final_df.to_csv("../climate_and_population_data.csv", index=False)